### ISSUE TITLE
Feature Request : Ajouter (pré)nom dans la carte

### ISSUE THREAD

**Issue by ooii** [delphiki/lovelace-pronote#1]
Bonjour,

Ce serait bien que l'en-tête de la carte affiche le nom et/ou prénom de l'enfant concerné par l'emploi du temps, pour pouvoir distinguer quand on a plusieurs enfants.
Merci.

**Comment by delphiki** [comment]
Hello,

Je vais voir pour rajouter ça, après je sais pas si je vais le mettre sur chaque carte, ça risque d'être redondant

**Comment by ooii** [comment]
Peut-être rajouter l'option que l'utilisateur mettre à true ou false ?
