### ISSUE TITLE
Feature Request : Ajouter en option le nombre de jours à afficher

### ISSUE THREAD

**Issue by ooii** [delphiki/lovelace-pronote#2]
Lorsqu'on met `sensor.pronote_xxx_timetable_period`, on a 2 semaines affichées. Ce serait bien d'avoir une option avec nombre de jours max à afficher.

**Comment by BreizhCat** [comment]
Bonjour,

Soit un nombre de jour, soit éventuellement la semaine en cours.

**Comment by delphiki** [comment]
Ces options ont été rajoutées dans la dernière release : https://github.com/delphiki/lovelace-pronote/releases/tag/1.1.0
