### ISSUE TITLE
Repository structure for 1.0.1 is not compliant

### ISSUE THREAD

**Issue by jfchadeyron** [delphiki/lovelace-pronote#3]
When i tried to add this repo in HACF, i have got this error : 
<Plugin delphiki/lovelace-pronote> Repository structure for 1.0.1 is not compliant

<img width="669" alt="Capture d’écran 2024-01-12 à 07 14 00" src="https://github.com/delphiki/lovelace-pronote/assets/78847492/871a5fdd-5330-4220-b224-51b450725b40">

**Comment by ooii** [comment]
You put the url of the repo web page, not the url of the repo itself.
Add https://github.com/delphiki/lovelace-pronote.git instead of https://github.com/delphiki/lovelace-pronote

**Comment by jfchadeyron** [comment]
Ok thanks. I pull a commit for the a readme.md to add this url

**Comment by delphiki** [comment]
It should be fixed now :)
